package Main;

import static Main.begin.mlm;
import javax.swing.JOptionPane;

public class ChangeProps extends java.awt.Dialog {
    private double recCommVal;
    private double sellCommVal;
    /**
     * Creates new form ChangeProps
     */
    public ChangeProps(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        passwordChange = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oldPassField = new javax.swing.JPasswordField();
        newPassField = new javax.swing.JPasswordField();
        oldKeyField = new javax.swing.JPasswordField();
        newKeyField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        keyChange = new javax.swing.JCheckBox();
        changeRecComm = new javax.swing.JCheckBox();
        passChangeButton = new javax.swing.JButton();
        keyChangeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        recCommValue = new javax.swing.JSpinner();
        commPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        recNewCommField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        recCommLimitField = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        recCommChangeButton = new javax.swing.JButton();
        recCommOKButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        commPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sellNewCommField = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sellCommLimitField = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        sellCommChangeButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        sellCommOKButton = new javax.swing.JButton();
        changeSellComm = new javax.swing.JCheckBox();
        sellCommValue = new javax.swing.JSpinner();
        changeFee = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        newFeeField = new javax.swing.JFormattedTextField();
        feeChangeButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        closeButton = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setResizable(false);
        setTitle("Change system properties");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        passwordChange.setText("Change the password");
        passwordChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordChangeActionPerformed(evt);
            }
        });

        jLabel1.setText("Current password:");

        jLabel2.setText("New password:");

        oldPassField.setEditable(false);

        newPassField.setEditable(false);

        oldKeyField.setEditable(false);

        newKeyField.setEditable(false);

        jLabel4.setText("Current key:");

        jLabel5.setText("New key:");

        keyChange.setText("Change the decryption key");
        keyChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyChangeActionPerformed(evt);
            }
        });

        changeRecComm.setText("Change the recruit commissions for a generation");
        changeRecComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeRecCommActionPerformed(evt);
            }
        });

        passChangeButton.setText("Change");
        passChangeButton.setEnabled(false);
        passChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passChangeButtonActionPerformed(evt);
            }
        });

        keyChangeButton.setText("Change");
        keyChangeButton.setEnabled(false);
        keyChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyChangeButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Change for generation");

        recCommValue.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        recCommValue.setEnabled(false);

        commPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setText("%");
        jLabel8.setToolTipText("");

        recNewCommField.setEditable(false);
        recNewCommField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel7.setText("Enter the new commission:");

        jLabel9.setText("(Must not exceed");

        recCommLimitField.setEditable(false);

        jLabel10.setText("%)");
        jLabel10.setToolTipText("");

        recCommChangeButton.setText("Change");
        recCommChangeButton.setEnabled(false);
        recCommChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recCommChangeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout commPanelLayout = new javax.swing.GroupLayout(commPanel);
        commPanel.setLayout(commPanelLayout);
        commPanelLayout.setHorizontalGroup(
            commPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(commPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recNewCommField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(commPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recCommLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recCommChangeButton)
                .addContainerGap())
        );
        commPanelLayout.setVerticalGroup(
            commPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(recNewCommField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(commPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(recCommLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recCommChangeButton)
                .addContainerGap())
        );

        recCommOKButton.setText("OK");
        recCommOKButton.setEnabled(false);
        recCommOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recCommOKButtonActionPerformed(evt);
            }
        });

        commPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel11.setText("%");
        jLabel11.setToolTipText("");

        sellNewCommField.setEditable(false);
        sellNewCommField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel12.setText("Enter the new commission:");

        jLabel13.setText("(Must not exceed");

        sellCommLimitField.setEditable(false);

        jLabel14.setText("%)");
        jLabel14.setToolTipText("");

        sellCommChangeButton.setText("Change");
        sellCommChangeButton.setEnabled(false);
        sellCommChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellCommChangeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout commPanel1Layout = new javax.swing.GroupLayout(commPanel1);
        commPanel1.setLayout(commPanel1Layout);
        commPanel1Layout.setHorizontalGroup(
            commPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(commPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellNewCommField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(commPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellCommLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sellCommChangeButton)
                .addContainerGap())
        );
        commPanel1Layout.setVerticalGroup(
            commPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sellNewCommField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(commPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sellCommLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sellCommChangeButton)
                .addContainerGap())
        );

        jLabel15.setText("Change for generation");

        sellCommOKButton.setText("OK");
        sellCommOKButton.setEnabled(false);
        sellCommOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellCommOKButtonActionPerformed(evt);
            }
        });

        changeSellComm.setText("Change the selling commissions for a generation");
        changeSellComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSellCommActionPerformed(evt);
            }
        });

        sellCommValue.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        sellCommValue.setEnabled(false);

        changeFee.setText("Change the recruit fee");
        changeFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFeeActionPerformed(evt);
            }
        });

        jLabel16.setText("Enter the new fee: RM");

        newFeeField.setEditable(false);
        newFeeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        feeChangeButton.setText("Change");
        feeChangeButton.setEnabled(false);
        feeChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeChangeButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(passwordChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(92, 92, 92))
                    .addComponent(oldPassField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPassField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(passChangeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addComponent(keyChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oldKeyField)
                    .addComponent(newKeyField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(keyChangeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeRecComm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(recCommValue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(recCommOKButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(commPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(11, 11, 11)))
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(changeSellComm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(commPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(11, 11, 11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sellCommValue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sellCommOKButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(44, 44, 44))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changeFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(feeChangeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newFeeField)))
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordChange)
                    .addComponent(keyChange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oldKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oldPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passChangeButton)
                    .addComponent(keyChangeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changeRecComm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(recCommValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recCommOKButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changeSellComm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(sellCommValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sellCommOKButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeFee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(newFeeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feeChangeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        
    }//GEN-LAST:event_closeDialog

    private void passwordChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordChangeActionPerformed
        if(passwordChange.isSelected()){
            oldPassField.setEditable(true);
            newPassField.setEditable(true);
            passChangeButton.setEnabled(true);
        }
        else{
            oldPassField.setText(null);
            newPassField.setText(null);
            oldPassField.setEditable(false);
            newPassField.setEditable(false);
            passChangeButton.setEnabled(false);
        }
    }//GEN-LAST:event_passwordChangeActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void passChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passChangeButtonActionPerformed
        try{
            if(oldPassField.getText().equals(mlm.getPassword()) && !newPassField.getText().equals("")){
                mlm.setPassword(newPassField.getText());
                oldPassField.setText(null);
                newPassField.setText(null);
                passwordChange.setSelected(false);
                oldPassField.setEditable(false);
                newPassField.setEditable(false);
                passChangeButton.setEnabled(false);
                JOptionPane.showMessageDialog(this,"Password successfully changed.");
            }
            else if(!oldPassField.getText().equals(mlm.getPassword())){
                JOptionPane.showMessageDialog(this,"Current password is incorrect.","Error",JOptionPane.ERROR_MESSAGE);
                oldPassField.setText(null);
            }
            else if(newPassField.getText().equals(""))
                JOptionPane.showMessageDialog(this,"New password cannot be empty.","Error",JOptionPane.ERROR_MESSAGE);
            else{
                JOptionPane.showMessageDialog(this,"Incorrect current password or invalid new password.","Error",JOptionPane.ERROR_MESSAGE);
                oldPassField.setText(null);
                newPassField.setText(null);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Invalid input.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_passChangeButtonActionPerformed

    private void keyChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyChangeActionPerformed
        try{
            if(keyChange.isSelected()){
                oldKeyField.setEditable(true);
                newKeyField.setEditable(true);
                keyChangeButton.setEnabled(true);
            }
            else{
                oldKeyField.setText(null);
                newKeyField.setText(null);
                oldKeyField.setEditable(false);
                newKeyField.setEditable(false);
                keyChangeButton.setEnabled(false);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Invalid input.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_keyChangeActionPerformed

    private void keyChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyChangeButtonActionPerformed
        if(oldKeyField.getText().equals(mlm.getdecryptkey()) && !newKeyField.getText().equals("")){
            mlm.setdecryptkey(newKeyField.getText());
            oldKeyField.setText(null);
            newKeyField.setText(null);
            keyChange.setSelected(false);
            oldKeyField.setEditable(false);
            newKeyField.setEditable(false);
            keyChangeButton.setEnabled(false);
            JOptionPane.showMessageDialog(this,"Decryption key successfully changed.");
        }
        else if(!oldKeyField.getText().equals(mlm.getdecryptkey())){
            JOptionPane.showMessageDialog(this,"Current key is incorrect.","Error",JOptionPane.ERROR_MESSAGE);
            oldKeyField.setText(null);
        }
        else if(newKeyField.getText().equals(""))
            JOptionPane.showMessageDialog(this,"New decryption key cannot be empty.","Error",JOptionPane.ERROR_MESSAGE);
        else{
            JOptionPane.showMessageDialog(this,"Incorrect current key or invalid new key.","Error",JOptionPane.ERROR_MESSAGE);
            oldKeyField.setText(null);
            newKeyField.setText(null);
        }
    }//GEN-LAST:event_keyChangeButtonActionPerformed

    private void changeRecCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeRecCommActionPerformed
        if(changeRecComm.isSelected()){
            recCommValue.setEnabled(true);
            recCommOKButton.setEnabled(true);
        }
        else{
            recCommValue.setValue(1);
            recCommLimitField.setText(null);
            recNewCommField.setText(null);
            recCommValue.setEnabled(false);
            recCommOKButton.setEnabled(false);
            recNewCommField.setEditable(false);
            recCommChangeButton.setEnabled(false);
        }
    }//GEN-LAST:event_changeRecCommActionPerformed

    private void recCommOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recCommOKButtonActionPerformed
        if(mlm.getGenerationRecruitRevenue((int)recCommValue.getValue(),mlm.getRoot(),0.0)==0)
            JOptionPane.showMessageDialog(this,"Generation does not exist.","Error",JOptionPane.ERROR_MESSAGE);
        else{
            recCommVal = 0.8;
            recNewCommField.setEditable(true);
            recCommChangeButton.setEnabled(true);
            for(int x=0;x<mlm.getRecruitCommissionSize();x++){
                recCommVal -= mlm.getRecruitCommission(x);
            }
            recCommVal += mlm.getRecruitCommission((int)recCommValue.getValue()-1);
            recCommLimitField.setText(Long.toString(Math.round((recCommVal)*100)));
        }
    }//GEN-LAST:event_recCommOKButtonActionPerformed

    private void recCommChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recCommChangeButtonActionPerformed
        try{
            if((Double.parseDouble(recNewCommField.getText()))/100>recCommVal)
                JOptionPane.showMessageDialog(this,"The new commission rate is above the "+Math.round((recCommVal)*100)+"% limit.","Error",JOptionPane.ERROR_MESSAGE);
            else{
                    mlm.setRecruitCommission((int)recCommValue.getValue()-1, (Double.parseDouble(recNewCommField.getText()))/100);
                    recCommValue.setValue(1);
                    recNewCommField.setText(null);
                    recCommLimitField.setText(null);
                    changeRecComm.setSelected(false);
                    recCommValue.setEnabled(false);
                    recCommOKButton.setEnabled(false);
                    recNewCommField.setEditable(false);
                    recCommChangeButton.setEnabled(false);
                    JOptionPane.showMessageDialog(this,"Recruit commission changed successfullly.");
                }
        }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Invalid input.","Error",JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_recCommChangeButtonActionPerformed

    private void changeSellCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSellCommActionPerformed
        if(changeSellComm.isSelected()){
            sellCommValue.setEnabled(true);
            sellCommOKButton.setEnabled(true);
        }
        else{
            sellCommValue.setValue(1);
            sellCommLimitField.setText(null);
            sellNewCommField.setText(null);
            sellCommValue.setEnabled(false);
            sellCommOKButton.setEnabled(false);
            sellNewCommField.setEditable(false);
            sellCommChangeButton.setEnabled(false);
        }
    }//GEN-LAST:event_changeSellCommActionPerformed

    private void sellCommOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellCommOKButtonActionPerformed
        if(mlm.getGenerationRecruitRevenue((int)sellCommValue.getValue(),mlm.getRoot(),0.0)==0)
            JOptionPane.showMessageDialog(this,"Generation does not exist.","Error",JOptionPane.ERROR_MESSAGE);
        else{
            sellCommVal = 0.5;
            sellNewCommField.setEditable(true);
            sellCommChangeButton.setEnabled(true);
            for(int x=0;x<mlm.getSalesCommissionSize();x++){
                sellCommVal -= mlm.getSalesCommission(x);
            }
            sellCommVal += mlm.getSalesCommission((int)sellCommValue.getValue()-1);
            sellCommLimitField.setText(Long.toString(Math.round((sellCommVal)*100)));
        }
    }//GEN-LAST:event_sellCommOKButtonActionPerformed

    private void sellCommChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellCommChangeButtonActionPerformed
        try{
            if((Double.parseDouble(sellNewCommField.getText()))/100>sellCommVal)
                JOptionPane.showMessageDialog(this,"The new commission rate is above the "+Math.round((sellCommVal)*100)+"% limit.","Error",JOptionPane.ERROR_MESSAGE);
            else{
                    mlm.setSalesCommission((int)sellCommValue.getValue()-1, (Double.parseDouble(sellNewCommField.getText()))/100);
                    sellCommValue.setValue(1);
                    sellNewCommField.setText(null);
                    sellCommLimitField.setText(null);
                    changeSellComm.setSelected(false);
                    sellCommValue.setEnabled(false);
                    sellCommOKButton.setEnabled(false);
                    sellNewCommField.setEditable(false);
                    sellCommChangeButton.setEnabled(false);
                    JOptionPane.showMessageDialog(this,"Sales commission changed successfullly.");
            }
        }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Invalid input","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sellCommChangeButtonActionPerformed

    private void changeFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFeeActionPerformed
        if(changeFee.isSelected()){
            newFeeField.setEditable(true);
            feeChangeButton.setEnabled(true);
        }
        else{
            newFeeField.setEditable(false);
            feeChangeButton.setEnabled(false);
        }
    }//GEN-LAST:event_changeFeeActionPerformed

    private void feeChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeChangeButtonActionPerformed
        try{
            if(Double.parseDouble(newFeeField.getText())<=0.00){
                newFeeField.setText(null);
                JOptionPane.showMessageDialog(this,"Invalid amount.","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                mlm.setFee(Double.parseDouble(newFeeField.getText()));
                newFeeField.setText(null);
                JOptionPane.showMessageDialog(this,"Fee changed successfullly.");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Invalid input.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_feeChangeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangeProps dialog = new ChangeProps(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox changeFee;
    private javax.swing.JCheckBox changeRecComm;
    private javax.swing.JCheckBox changeSellComm;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel commPanel;
    private javax.swing.JPanel commPanel1;
    private javax.swing.JButton feeChangeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox keyChange;
    private javax.swing.JButton keyChangeButton;
    private javax.swing.JFormattedTextField newFeeField;
    private javax.swing.JPasswordField newKeyField;
    private javax.swing.JPasswordField newPassField;
    private javax.swing.JPasswordField oldKeyField;
    private javax.swing.JPasswordField oldPassField;
    private javax.swing.JButton passChangeButton;
    private javax.swing.JCheckBox passwordChange;
    private javax.swing.JButton recCommChangeButton;
    private javax.swing.JFormattedTextField recCommLimitField;
    private javax.swing.JButton recCommOKButton;
    private javax.swing.JSpinner recCommValue;
    private javax.swing.JFormattedTextField recNewCommField;
    private javax.swing.JButton sellCommChangeButton;
    private javax.swing.JFormattedTextField sellCommLimitField;
    private javax.swing.JButton sellCommOKButton;
    private javax.swing.JSpinner sellCommValue;
    private javax.swing.JFormattedTextField sellNewCommField;
    // End of variables declaration//GEN-END:variables
}
